### ISSUE TITLE
Add GithUb actions

### ISSUE THREAD

**Issue by JulianFeinauer** [pragmaticindustries/pql-demo#4]

**Comment by JulianFeinauer** [comment]
@NiklasMerz magst du Simon ein wenig bei seinem Abschlussarbeitsprojekt helfen?
Bruachen nur eine kleine gh action für das übliche... flake, black, pytest, ...

**Comment by NiklasMerz** [comment]
Klar kann ich machen. Was das Python Zeug angeht habe ich aber auch nicht so die Ahnung. Dieses Template sieht aber ganz gut aus da können wir uns die Actions nachbauen: https://github.com/jenstroeger/python-package-template

**Comment by JulianFeinauer** [comment]
Ja sowas in der Art, coolio

**Comment by pragmayticer** [comment]
Jo @JulianFeinauer schau mal in der Main da hab ich Actions rein und close dann das Issue
